version: "3.9"

services:
  consul:
    image: bitnami/consul
    container_name: "gws-consul"
    ports:
      - "8501:8500"
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
      - ./resources/consul:/resources/consul
    command:
      - sh
      - -c
      - |
        consul agent -server -ui -bind 0.0.0.0 -client 0.0.0.0 -data-dir /consul/data -config-dir /consul/config -bootstrap -datacenter docker &
        consul_pid=$!
        sleep 5
        consul kv import -http-addr=http://0.0.0.0:8500 @/resources/consul/consul-config-kv.json
        wait $consul_pid


  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Olimp123
      - POSTGRES_DB=social_media
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  producer:
    image: xnenonx/unit2:latest
    ports:
      - "1001:1001"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social_media
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Olimp123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_APPLICATION_NAME: service-unit2
      SERVER_PORT: 1001
    depends_on:
      - postgres
      - kafka

  nodejs:
    image: xnenonx/nodejs:latest
    ports:
      - '1002:1002'
    restart: on-failure
    depends_on:
      - db
      - consul
    environment:
      NODE_ENV: prod
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    command: sh -c "sleep 15 && node dist/index.js"

  db:
    image: mongo:5.0.14
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  react-app:
    image: xnenonx/react-app:latest
    ports:
      - '1003:80'

  gateway:
    image: xnenonx/gateway:latest
    ports:
      - '1000:1000'
    environment:
      SERVER_PORT: 1000
      SPRING_APPLICATION_NAME: gateway
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      - consul


networks:
  default:
    name: gws-net
    driver: bridge
